version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Update 'VARIANT' to pick a .NET version
        # Update 'VARIANT' to pick a .NET Core version: 3.1, 5.0, 6.0
        # Append -bullseye or -focal to pin to an OS version.
        # https://mcr.microsoft.com/v2/dotnet/sdk/tags/list
        VARIANT: "6.0"
        # Options
        # INSTALL_ZSH: "true"
        # UPGRADE_PACKAGES: "true"
        NODE_VERSION: "lts/*"
        
    environment:
      ASPNETCORE_URLS: "https://+:5001;http://+:5000"
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1

    volumes:
      - ..:/workspace:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: host

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

# networks:
#   default:
#     external:
#       name: bridge