services:
  db:
      # container_name: sql
      image: mcr.microsoft.com/azure-sql-edge:latest

      environment:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: P@ssw0rd
        MSSQL_PID: Developer

      ports:
        - 1433:1433
      
      volumes:
        - sql-data:/data
      
      # Overrides default command so things don't shut down after the process ends.
      # command: sleep infinity

      # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
      # network_mode: host

      # Uncomment the next line to use a non-root user for all processes.
      # user: vscode

volumes:
  sql-data:

# networks:
#   default:
#     external:
#       name: bridge