source 'https://rubygems.org'

# https://github.com/github/pages-gem/issues/752
# gem 'webrick'

# If you have any plugins, put them here!
# Refer GitHub Pages version dependencies from https://pages.github.com/versions.json
gem "github-pages", "225", group: :jekyll_plugins

group :jekyll_plugins do
  gem 'json'
  gem 'jemoji'
  gem 'jekyll-feed'
  gem 'jekyll-sitemap'
  gem 'jekyll-redirect-from'
  gem 'jekyll-remote-theme'
end
