source 'https://rubygems.org'

# https://github.com/github/pages-gem/issues/752
# gem 'webrick'

# If you have any plugins, put them here!
gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  # gem "jekyll"
  gem 'jemoji'
  gem 'jekyll-feed'
  gem 'jekyll-sitemap'
  gem 'jekyll-redirect-from'
  gem 'jekyll-remote-theme'
end
